### PR TITLE
Add loopback-connector-firestore to connectors

### PR DESCRIPTION
**Pull request by dyaa**
https://github.com/dyaa/loopback-connector-firestore

---
This change is [Reviewable](https://reviewable.io/reviews/pasindud/awesome-loopback/25)

### CODE REVIEW

**Comment by dyaa** [comment]
Any updates !

**Comment by pasindud** [comment]
I have commented on the code

**Comment by dyaa** [comment]
@pasindud where?

**Comment by pasindud** [comment]
@dyaa oh sorry my bad it seems it was not submitted

**Comment by dyaa** [comment]
Done

**Comment by pasindud** [comment]
👍

**Pull request merged**
